decoy_deep_sea_optimistic_nash_v_tune:
    iterations: 500
    eval_interval: 1
    num_games: 4
    num_runs: 1
    # ==== Game ====
    game: decoy_deep_sea
    game_config:
        decoy_games: 
            grid_search: [10, 30]
        decoy_size: 
            grid_search: [10, 20]
        decoy_payoff: 1.
        target_payoff: 1.
        target_penalty: 0.0
        adversary_payoff: 0.5
    # ==== Algorithm ====
    alg: optimistic_nash_v
    alg_config: 
        iteration_episodes: 100
        gamma: 
            grid_search: [0.1, 0.5]
        eta:
            grid_search: [0.1, 0.5, 10.0, 100.0]
        beta: 
            grid_search: [0.0, 1.0]
        averaging:
            grid_search: [False, True]