decoy_deep_sea_optimistic_nash_q:
    iterations: 2000
    eval_interval: 10
    num_games: 10
    num_runs: 1
    # ==== Game ====
    game: decoy_deep_sea
    game_config:
        decoy_games: 
            grid_search: [10, 20, 30, 40, 50]
        decoy_size: 
            grid_search: [10, 20]
        decoy_payoff: 1.
        target_payoff: 1.
        target_penalty: 0.0
        adversary_payoff: 0.5
    # ==== Algorithm ====
    alg: optimistic_nash_q
    alg_config: 
        iteration_episodes: 10
        beta: 0.0
        exploit:
            grid_search: [False, True]
        averaging: True